### ISSUE TITLE
No meson version requirement specified

### ISSUE THREAD

**Issue by mpoquet** [netorcai/netorcai-client-fortran#10]
While trying to package this library, I found out it does not work with old meson.

`meson_version` should be specified (see [meson documentation](https://mesonbuild.com/Reference-manual.html#project)).

**Comment by zephyr111** [comment]
Do you know the last version of meson that does not work?

**Comment by mpoquet** [comment]
- 0.49.2 : OK
- 0.49.1 : OK
- 0.49.0 : OK
- 0.48.0 : OK
- 0.47.0 : OK
- 0.46.0 : **FAILURE** (problems about finding `.mod` files)
