### ISSUE TITLE
Release for netorcai-2.0.0?

### ISSUE THREAD

**Issue by mpoquet** [netorcai/netorcai-client-fortran#11]
Is the last release compatible with [netorcai-2.0.0](https://netorcai.readthedocs.io/en/latest/changelog.html#v2-0-0) that has been released today?
If not, can you please release a new version? Thanks!

**Comment by zephyr111** [comment]
v0.1.0 should be already compatible with netorcai-2.0.0.
The v0.2.0 fix some bugs and is currently up to date.
