### ISSUE TITLE
examples

### ISSUE THREAD

**Issue by mpoquet** [netorcai/netorcai-client-fortran#2]
Hello,

As 43fc743, there are no external examples for `netorcai-client-fortran` :(.
This would provide a kind of "getting started" so users know how to use the library once it is installed — I for example need this to implement a FORTRAN client for a specific game.

As an example, netorcai-client-cpp gives example projects to create a [basic game logic client](https://github.com/netorcai/netorcai-client-cpp/tree/master/examples/hello-gl) or a [basic player client](https://github.com/netorcai/netorcai-client-cpp/tree/master/examples/hello-player).

**Comment by zephyr111** [comment]
It should be OK now.
Reopen if needed.
