### ISSUE TITLE
Protocol version handshake

### ISSUE THREAD

**Issue by mpoquet** [netorcai/netorcai-client-fortran#3]
Hello,

The FORTRAN library does not work with up-to-date netorcai, as a protocol version handshake has been implemented. As an example, [here](https://github.com/netorcai/netorcai-client-java/commit/f367b2e50585d669cc577b36c94de90f16bc1b00) are the changes that were needed for the Java™ client library.

**Comment by zephyr111** [comment]
Thank you for your endless interest in improving further this FORTRAN implementation.
It now supports this feature also added in the Java™ version.
