### ISSUE TITLE
UTF-8 parsing error

### ISSUE THREAD

**Issue by mpoquet** [netorcai/netorcai-client-fortran#9]
While the project README states that non-ASCII UTF-8 characters are replaced by `?`, receiving Japanese characters issues a parsing error.

#### How to reproduce?
1. Run netorcai.
2. Run a game logic. As the provided FORTRAN example does not compile on my machine (#8), I used the [hello-gl python example](https://github.com/netorcai/netorcai-client-python/blob/master/examples/hello-gl/hello-gl.py).
3. Run a visualization client using the FORTRAN library. There is one in PR #7.
4. Run a player client named `プレーヤー`. A full python example of such a client is given below.
    **If an ASCII player name is used, the FORTRAN visualization client does not crash.**
5. Run the game (e.g., by entering `start` in netorcai's prompt).

#### FORTRAN visualization client log
```
./hello-visu
 Connecting to netorcai...
 done
 Logging in as a visualization...
 done
 Waiting for GAME_STARTS...
 Parse error
STOP 1
```

### Japanese python player
```python
#!/usr/bin/env python3
from netorcai.client import *
import sys

def main():
    try:
        client = Client()

        print("Connecting to netorcai...", end=' ', flush=True)
        client.connect()
        print("done")

        print("Logging in as a player...", end=' ', flush=True)
        client.send_login("プレーヤー", "player")
        client.read_login_ack()
        print("done")

        print("Waiting for GAME_STARTS...", end=' ', flush=True)
        game_starts = client.read_game_starts()
        print("done")

        for i in range(game_starts.nb_turns_max):
            print("Waiting for TURN...", end=' ', flush=True)
            turn = client.read_turn()
            print("done")

            actions = [{"player": "python"}]
            print("Sending actions {}...".format(actions), end=' ', flush=True)
            client.send_turn_ack(turn.turn_number, actions)
            print("done")
    except Exception as e:
        print(e)
        sys.exit(1)
    sys.exit(0)

if __name__ == '__main__':
    main()

```

**Comment by zephyr111** [comment]
This was a problem with UTF-8 characters received directly from the network.
It is now fixed: unicode code points are replaced with '?' ones. 
Thank you.
